/** Self-identification for intake (searchable multi-select). */
export const ETHNICITY_OPTIONS: string[] = [
  'White',
  'Black',
  'African American',
  'African',
  'Caribbean',
  'Mexican',
  'Central American',
  'South American',
  'Puerto Rican',
  'Cuban',
  'Dominican',
  'East Asian',
  'Southeast Asian',
  'South Asian',
  'Arab',
  'Middle Eastern',
  'Iranian / Persian',
  'North African',
  'Native American',
  'Pacific Islander',
  'Other',
  'Prefer not to say',
]
