/**
 * Colleges and universities in the Greater Los Angeles area (within ~50 mile radius).
 * Uses common abbreviations / how people usually refer to them.
 */
export const LA_COLLEGES: string[] = [
  'American Jewish University',
  'Antelope Valley College',
  'ArtCenter College of Design',
  'Azusa Pacific University (APU)',
  'Biola University',
  'Cal Poly Pomona',
  'Cal State Dominguez Hills',
  'Cal State Fullerton',
  'Cal State LA',
  'Cal State Long Beach',
  'Cal State Northridge',
  'CalArts',
  'Caltech',
  'California Lutheran University (CLU)',
  'Cerritos College',
  'Chapman University',
  'Charles R. Drew University',
  'Citrus College',
  'Claremont Graduate University (CGU)',
  'Claremont McKenna College (CMC)',
  'College of the Canyons',
  'Compton College',
  'Concordia University Irvine',
  'East Los Angeles College (ELAC)',
  'El Camino College',
  'Fullerton College',
  'Glendale Community College',
  'Harvey Mudd College',
  'Hope International University',
  'Irvine Valley College',
  'La Sierra University',
  'Long Beach City College',
  'Los Angeles City College (LACC)',
  'Los Angeles Harbor College',
  'Los Angeles Mission College',
  'Los Angeles Pierce College',
  'Los Angeles Southwest College',
  'Los Angeles Trade-Technical College (LATTC)',
  'Los Angeles Valley College (LAVC)',
  'Loyola Marymount University (LMU)',
  'Marymount California University',
  'Mission College',
  'Mount Saint Mary\'s University',
  'Mt. San Antonio College (Mt. SAC)',
  'Occidental College (Oxy)',
  'Orange Coast College',
  'Otis College of Art and Design',
  'Pasadena City College (PCC)',
  'Pepperdine University',
  'Pitzer College',
  'Pomona College',
  'Rio Hondo College',
  'Saddleback College',
  'Santa Ana College',
  'Santa Monica College (SMC)',
  'Scripps College',
  'Soka University of America',
  'Southwestern Law School',
  'UC Irvine',
  'UCLA',
  'University of La Verne',
  'University of Redlands',
  'USC',
  'Vanguard University',
  'West Los Angeles College',
  'Westmont College',
  'Whittier College',
  'Woodbury University',
  'Other',
  'Prefer not to say',
]
