/**
 * Common undergraduate majors for dropdown. No slashes.
 */
export const MAJORS: string[] = [
  'Accounting',
  'Advertising',
  'Aerospace Engineering',
  'African American Studies',
  'Agriculture',
  'American Studies',
  'Anthropology',
  'Architecture',
  'Art History',
  'Art and Design',
  'Biochemistry',
  'Biology',
  'Biomedical Engineering',
  'Business Administration',
  'Chemical Engineering',
  'Chemistry',
  'Civil Engineering',
  'Communications',
  'Computer Engineering',
  'Computer Science',
  'Criminal Justice',
  'Dance',
  'Economics',
  'Education',
  'Electrical Engineering',
  'English',
  'Environmental Science',
  'Environmental Studies',
  'Exercise Science',
  'Film and Media',
  'Finance',
  'Fine Arts',
  'Graphic Design',
  'Health Sciences',
  'History',
  'Hospitality Management',
  'Human Resources',
  'Industrial Engineering',
  'International Relations',
  'Journalism',
  'Kinesiology',
  'Landscape Architecture',
  'Liberal Arts',
  'Linguistics',
  'Marketing',
  'Mathematics',
  'Mechanical Engineering',
  'Music',
  'Neuroscience',
  'Nursing',
  'Nutrition',
  'Philosophy',
  'Physics',
  'Political Science',
  'Pre-Law',
  'Pre-Med',
  'Psychology',
  'Public Health',
  'Public Policy',
  'Social Work',
  'Sociology',
  'Software Engineering',
  'Spanish',
  'Sports Management',
  'Studio Art',
  'Theater',
  'Urban Planning',
  'Other',
  'Prefer not to say',
]
