/**
 * City markets for Fika: groups of cities that share a 250-person threshold for opt-in.
 * Used for profile count and "building community in [city]" messaging.
 * Santa Monica, Culver City, etc. count as Los Angeles.
 */

export const TARGET_COUNT_PER_MARKET = 250

export interface Market {
  slug: string
  label: string
  /** Lowercase substrings; profile city is matched case-insensitive. Any match assigns this market. */
  cityPatterns: string[]
}

export const MARKETS: Market[] = [
  {
    slug: 'orange-county',
    label: 'Orange County',
    cityPatterns: [
      'anaheim',
      'orange',
      'irvine',
      'costa mesa',
      'huntington beach',
      'newport beach',
      'tustin',
      'santa ana',
      'garden grove',
      'westminster',
      'fountain valley',
      'mission viejo',
      'lake forest',
      'rancho santa margarita',
      'fullerton',
      'la habra',
      'laguna niguel',
      'dana point',
      'laguna beach',
      'san clemente',
      'aliso viejo',
      'laguna hills',
      'yorba linda',
      'placentia',
      'brea',
      'cypress',
      'los alamitos',
      'seal beach',
      'buena park',
      'la palma',
      'stanton',
      'villa park',
    ],
  },
  {
    slug: 'ie',
    label: 'Inland Empire',
    cityPatterns: [
      'inland empire',
      'riverside',
      'san bernardino',
      'ontario',
      'rancho cucamonga',
      'corona',
      'fontana',
      'moreno valley',
      'rialto',
      'redlands',
      'hesperia',
      'victorville',
      'temecula',
      'murrieta',
      'menifee',
      'hemet',
      'perris',
      'colton',
      'upland',
      'chino',
      'chino hills',
      'highland',
      'apple valley',
      'yucaipa',
      'lake elsinore',
      'wildomar',
      'norco',
      'eastvale',
      'jurupa valley',
      'montclair',
      'pomona',
      'claremont',
      'la verne',
      'san dimas',
      'glendora',
      'azusa',
      'covina',
      'west covina',
      'diamond bar',
      'walnut',
      'rowland heights',
    ],
  },
  {
    slug: 'la',
    label: 'Los Angeles',
    cityPatterns: [
      'los angeles',
      'santa monica',
      'culver city',
      'pasadena',
      'burbank',
      'glendale',
      'long beach',
      'santa clarita',
      'inglewood',
      'culver',
      'marina del rey',
      'venice',
      'hollywood',
      'west hollywood',
      'sherman oaks',
      'studio city',
      'encino',
      'north hollywood',
      'van nuys',
      'south pasadena',
      'alhambra',
      'monrovia',
      'arcadia',
      'el monte',
      'downey',
      'torrance',
      'redondo beach',
      'manhattan beach',
      'hermosa beach',
      'inglewood',
      'compton',
      'gardena',
      'hawthorne',
      'lawndale',
      'inglewood',
      'lynwood',
      'south gate',
      'lakewood',
      'signal hill',
      'bellflower',
      'cerritos',
      'norwalk',
      'whittier',
      'la mirada',
    ],
  },
  {
    slug: 'sf',
    label: 'San Francisco',
    cityPatterns: [
      'san francisco',
      'sf,',
      'oakland',
      'berkeley',
      'san jose',
      'palo alto',
      'mountain view',
      'sunnyvale',
      'san mateo',
      'daly city',
      'south san francisco',
      'dublin',
      'pleasanton',
      'fremont',
      'hayward',
      'alameda',
      'emeryville',
      'sausalito',
      'mill valley',
      'san rafael',
      'richmond',
      'el cerrito',
      'alameda',
      'walnut creek',
      'concord',
      'san leandro',
    ],
  },
  {
    slug: 'nyc',
    label: 'New York City',
    cityPatterns: [
      'new york',
      'nyc',
      'brooklyn',
      'manhattan',
      'queens',
      'bronx',
      'staten island',
      'long island city',
      'williamsburg',
      'bushwick',
      'harlem',
      'upper east',
      'upper west',
      'tribeca',
      'soho',
      'greenpoint',
      'dumbo',
      'park slope',
      'jersey city',
      'hoboken',
      'weehawken',
    ],
  },
  {
    slug: 'chicago',
    label: 'Chicago',
    cityPatterns: [
      'chicago',
      'evanston',
      'oak park',
      'naperville',
      'aurora il',
      'aurora illinois',
      'joliet',
      'schaumburg',
      'skokie',
      'des plaines',
      'arlington heights',
      'palatine',
      'cicero',
      'berwyn',
      'waukegan',
      'champaign',
      'urbana',
      'bloomington',
      'normal',
      'dekalb',
    ],
  },
  {
    slug: 'houston',
    label: 'Houston',
    cityPatterns: [
      'houston',
      'the woodlands',
      'sugar land',
      'pearland',
      'baytown',
      'pasadena',
      'league city',
      'galveston',
      'conroe',
      'katy',
      'cypress',
      'spring',
      'humble',
      'kingwood',
    ],
  },
  {
    slug: 'phoenix',
    label: 'Phoenix',
    cityPatterns: [
      'phoenix',
      'scottsdale',
      'mesa',
      'tempe',
      'chandler',
      'gilbert',
      'glendale',
      'peoria',
      'surprise',
      'queen creek',
      'goodyear',
      'avondale',
      'flagstaff',
      'tucson',
    ],
  },
  {
    slug: 'philadelphia',
    label: 'Philadelphia',
    cityPatterns: [
      'philadelphia',
      'philly',
      'camden',
      'cherry hill',
      'wilmington',
      'reading',
      'allentown',
      'bethlehem',
      'chester',
      'norristown',
      'upper darby',
      'bensalem',
      'lower merion',
      'conshohocken',
      'manayunk',
      'fishtown',
    ],
  },
  {
    slug: 'san-antonio',
    label: 'San Antonio',
    cityPatterns: [
      'san antonio',
      'new braunfels',
      'schertz',
      'universal city',
      'live oak',
      'alamo heights',
      'helotes',
    ],
  },
  {
    slug: 'san-diego',
    label: 'San Diego',
    cityPatterns: [
      'san diego',
      'chula vista',
      'oceanside',
      'carlsbad',
      'el cajon',
      'vista',
      'san marcos',
      'encinitas',
      'national city',
      'la mesa',
      'poway',
      'santee',
      'coronado',
      'del mar',
      'la jolla',
      'mission valley',
    ],
  },
  {
    slug: 'dallas',
    label: 'Dallas–Fort Worth',
    cityPatterns: [
      'dallas',
      'fort worth',
      'arlington',
      'plano',
      'garland',
      'irving',
      'frisco',
      'mckinney',
      'grand prairie',
      'denton',
      'lewisville',
      'carrollton',
      'richardson',
      'allen',
      'flower mound',
      'north richland hills',
      'euless',
      'bedford',
      'grapevine',
      'keller',
      'southlake',
      'colleyville',
      'addison',
    ],
  },
  {
    slug: 'austin',
    label: 'Austin',
    cityPatterns: [
      'austin',
      'round rock',
      'cedar park',
      'georgetown',
      'pflugerville',
      'kyle',
      'buda',
      'lakeway',
      'bee cave',
      'west lake',
      'travis county',
    ],
  },
  {
    slug: 'jacksonville',
    label: 'Jacksonville',
    cityPatterns: [
      'jacksonville',
      'jacksonville beach',
      'atlantic beach',
      'neptune beach',
      'orange park',
      'st augustine',
      'fernandina',
    ],
  },
  {
    slug: 'columbus',
    label: 'Columbus',
    cityPatterns: [
      'columbus',
      'upper arlington',
      'gahanna',
      'reynoldsburg',
      'grove city',
      'hilliard',
      'westerville',
      'delaware',
      'worthington',
      'new albany',
      'powell',
    ],
  },
  {
    slug: 'charlotte',
    label: 'Charlotte',
    cityPatterns: [
      'charlotte',
      'huntersville',
      'matthews',
      'gastonia',
      'concord',
      'kannapolis',
      'rock hill',
      'fort mill',
      'mooresville',
      'south end',
      'noda',
      'plaza midwood',
    ],
  },
  {
    slug: 'indianapolis',
    label: 'Indianapolis',
    cityPatterns: [
      'indianapolis',
      'carmel',
      'fishers',
      'noblesville',
      'greenwood',
      'lawrence',
      'greenfield',
      'zionsville',
      'speedway',
      'broad ripple',
    ],
  },
  {
    slug: 'seattle',
    label: 'Seattle',
    cityPatterns: [
      'seattle',
      'bellevue',
      'tacoma',
      'everett',
      'kent',
      'renton',
      'kirkland',
      'redmond',
      'sammamish',
      'issaquah',
      'federal way',
      'shoreline',
      'bothell',
      'edmonds',
      'lynwood',
      'mukilteo',
      'covington',
      'burien',
      'des moines',
      'tukwila',
      'capitol hill',
      'ballard',
      'fremont',
      'queen anne',
    ],
  },
  {
    slug: 'denver',
    label: 'Denver',
    cityPatterns: [
      'denver',
      'aurora',
      'lakewood',
      'thornton',
      'arvada',
      'westminster',
      'centennial',
      'boulder',
      'fort collins',
      'greeley',
      'loveland',
      'englewood',
      'littleton',
      'golden',
      'wheat ridge',
      'cherry creek',
      'capitol hill',
      'lodo',
      'rino',
      'highlands',
    ],
  },
  {
    slug: 'boston',
    label: 'Boston',
    cityPatterns: [
      'boston',
      'cambridge',
      'somerville',
      'brookline',
      'quincy',
      'newton',
      'waltham',
      'lexington',
      'arlington',
      'watertown',
      'medford',
      'everett',
      'chelsea',
      'revere',
      'malden',
      'salem',
      'beverly',
      'lowell',
      'worcester',
      'providence',
      'back bay',
      'south end',
      'cambridgeport',
      'harvard square',
      'downtown crossing',
    ],
  },
  {
    slug: 'nashville',
    label: 'Nashville',
    cityPatterns: [
      'nashville',
      'franklin',
      'brentwood',
      'hendersonville',
      'murfreesboro',
      'smyrna',
      'mount juliet',
      'gallatin',
      'antioch',
      'bellevue',
      'east nashville',
      'the gulch',
      '12 south',
      'green hills',
    ],
  },
  {
    slug: 'detroit',
    label: 'Detroit',
    cityPatterns: [
      'detroit',
      'ann arbor',
      'dearborn',
      'troy',
      'warren',
      'sterling heights',
      'livonia',
      'southfield',
      'farmington',
      'royal oak',
      'berkley',
      'ferndale',
      'birmingham',
      'grosse pointe',
      'midtown',
      'corktown',
      'downtown',
    ],
  },
  {
    slug: 'portland',
    label: 'Portland',
    cityPatterns: [
      'portland',
      'beaverton',
      'hillsboro',
      'gresham',
      'lake oswego',
      'tigard',
      'tualatin',
      'oregon city',
      'milwaukie',
      'vancouver',
      'camas',
      'pearl district',
      'nob hill',
      'hawthorne',
      'division',
      'mississippi',
      'alberta',
    ],
  },
  {
    slug: 'las-vegas',
    label: 'Las Vegas',
    cityPatterns: [
      'las vegas',
      'henderson',
      'north las vegas',
      'summerlin',
      'spring valley',
      'paradise',
      'boulder city',
      'mesquite',
    ],
  },
  {
    slug: 'baltimore',
    label: 'Baltimore',
    cityPatterns: [
      'baltimore',
      'towson',
      'columbia',
      'ellicott city',
      'glen burnie',
      'dundalk',
      'canton',
      'fells point',
      'mount vernon',
      'hampden',
      'federal hill',
      'inner harbor',
    ],
  },
  {
    slug: 'milwaukee',
    label: 'Milwaukee',
    cityPatterns: [
      'milwaukee',
      'waukesha',
      'west allis',
      'brookfield',
      'greenfield',
      'wauwatosa',
      'shorewood',
      'whitefish bay',
      'mequon',
      'third ward',
      'east side',
      'brady street',
    ],
  },
  {
    slug: 'albuquerque',
    label: 'Albuquerque',
    cityPatterns: [
      'albuquerque',
      'rio rancho',
      'santa fe',
      'los lunas',
      'bernalillo',
      'nob hill',
      'downtown',
      'old town',
    ],
  },
  {
    slug: 'sacramento',
    label: 'Sacramento',
    cityPatterns: [
      'sacramento',
      'elk grove',
      'roseville',
      'citrus heights',
      'rancho cordova',
      'folsom',
      'davis',
      'woodland',
      'west sacramento',
      'midtown',
      'east sacramento',
      'land park',
      'tahoe park',
    ],
  },
  {
    slug: 'atlanta',
    label: 'Atlanta',
    cityPatterns: [
      'atlanta',
      'decatur',
      'sandy springs',
      'roswell',
      'alpharetta',
      'marietta',
      'smyrna',
      'dunwoody',
      'brookhaven',
      'chamblee',
      'east point',
      'college park',
      'buckhead',
      'midtown',
      'east atlanta',
      'virginia-highland',
      'little five points',
      'inman park',
      'candler park',
      'grant park',
    ],
  },
  {
    slug: 'kansas-city',
    label: 'Kansas City',
    cityPatterns: [
      'kansas city',
      'kansas city mo',
      'kansas city ks',
      'overland park',
      'olathe',
      'independence',
      'lee\'s summit',
      'lees summit',
      'shawnee',
      'blue springs',
      'liberty',
      'north kansas city',
      'river market',
      'crossroads',
      'westport',
      'brookside',
      'waldo',
    ],
  },
  {
    slug: 'miami',
    label: 'Miami',
    cityPatterns: [
      'miami',
      'miami beach',
      'fort lauderdale',
      'hollywood',
      'pembroke pines',
      'coral springs',
      'boca raton',
      'west palm beach',
      'delray beach',
      'brickell',
      'wynwood',
      'little havana',
      'coconut grove',
      'coral gables',
      'key biscayne',
      'south beach',
      'kendall',
      'doral',
      'hialeah',
      'aventura',
    ],
  },
  {
    slug: 'raleigh',
    label: 'Raleigh–Durham',
    cityPatterns: [
      'raleigh',
      'durham',
      'chapel hill',
      'cary',
      'apex',
      'holly springs',
      'wake forest',
      'garner',
      'morrisville',
      'research triangle',
      'downtown raleigh',
      'downtown durham',
      'north hills',
      'glenwood south',
    ],
  },
  {
    slug: 'minneapolis',
    label: 'Minneapolis–Saint Paul',
    cityPatterns: [
      'minneapolis',
      'saint paul',
      'st paul',
      'bloomington',
      'brooklyn park',
      'plymouth',
      'woodbury',
      'maple grove',
      'eden prairie',
      'edina',
      'minnetonka',
      'st louis park',
      'richfield',
      'uptown',
      'north loop',
      'northeast',
      'dinkytown',
      'grand avenue',
      'highland park',
      'summit hill',
    ],
  },
  {
    slug: 'cleveland',
    label: 'Cleveland',
    cityPatterns: [
      'cleveland',
      'cleveland heights',
      'lakewood',
      'euclid',
      'parma',
      'elyria',
      'mentor',
      'strongsville',
      'westlake',
      'fairview park',
      'tremont',
      'ohio city',
      'detroit shoreway',
      'covington',
      'little italy',
    ],
  },
  {
    slug: 'tampa',
    label: 'Tampa Bay',
    cityPatterns: [
      'tampa',
      'st petersburg',
      'saint petersburg',
      'clearwater',
      'brandon',
      'lutz',
      'temple terrace',
      'south tampa',
      'hyde park',
      'ybor city',
      'downtown tampa',
      'gulfport',
      'dunedin',
      'safety harbor',
    ],
  },
  {
    slug: 'st-louis',
    label: 'St. Louis',
    cityPatterns: [
      'st louis',
      'saint louis',
      'st. louis',
      'chesterfield',
      'ballwin',
      'florissant',
      'university city',
      'webster groves',
      'kirkwood',
      'maryland heights',
      'creve coeur',
      'soulard',
      'central west end',
      'the loop',
      'tower grove',
      'lafayette square',
    ],
  },
  {
    slug: 'pittsburgh',
    label: 'Pittsburgh',
    cityPatterns: [
      'pittsburgh',
      'pittsburg',
      'mount lebanon',
      'bethel park',
      'ross township',
      'mccandless',
      'monroeville',
      'cranberry',
      'shadyside',
      'squirrel hill',
      'lawrenceville',
      'strip district',
      'south side',
      'oakland',
      'downtown',
    ],
  },
  {
    slug: 'cincinnati',
    label: 'Cincinnati',
    cityPatterns: [
      'cincinnati',
      'covington',
      'newport',
      'norwood',
      'hyde park',
      'oakley',
      'clifton',
      'over-the-rhine',
      'downtown',
      'mount adams',
      'northside',
      'walnut hills',
      'anderson',
      'mason',
      'west chester',
      'fairfield',
    ],
  },
  {
    slug: 'orlando',
    label: 'Orlando',
    cityPatterns: [
      'orlando',
      'winter park',
      'kissimmee',
      'sanford',
      'altamonte springs',
      'oviedo',
      'lake mary',
      'downtown orlando',
      'thornton park',
      'mills 50',
      'audubon park',
      'college park',
      'winter garden',
      'dr phillips',
    ],
  },
]

const slugToMarket = new Map(MARKETS.map((m) => [m.slug, m]))

/** Normalize city for matching: lowercase, trim. */
function normalizeCity(city: string | null | undefined): string {
  if (city == null || typeof city !== 'string') return ''
  return city.trim().toLowerCase()
}

/**
 * Return the market for a profile's city (and optionally lat/lng in future).
 * Santa Monica, Culver City, etc. → LA. Unknown cities return null.
 */
export function getMarketFromCity(city: string | null | undefined): { slug: string; label: string } | null {
  const normalized = normalizeCity(city)
  if (!normalized) return null
  for (const market of MARKETS) {
    if (market.cityPatterns.some((p) => normalized.includes(p))) return { slug: market.slug, label: market.label }
  }
  return null
}

export function getMarketBySlug(slug: string | null | undefined): Market | null {
  if (slug == null || typeof slug !== 'string') return null
  return slugToMarket.get(slug.trim().toLowerCase()) ?? null
}
