// LA Beta onboarding: Profile + Intake (Final). No maxes on multi_select.
// Types: text | date | chips_single | location_permission | multi_select

export type StepType =
  | 'text'
  | 'date'
  | 'chips_single'
  | 'location_permission'
  | 'multi_select'

export type ProfileStep = {
  id: string
  question: string
  type: StepType
  body?: string
  required?: boolean
  options?: string[]
  placeholder?: string
  minAge?: number
  maxSelections?: number
  minSelections?: number
}

// PROFILE: name, demographics, location
export const PROFILE_STEPS: ProfileStep[] = [
  {
    id: 'first_name',
    question: "What's your first name?",
    type: 'text',
    required: true,
    placeholder: 'Your name',
  },
  {
    id: 'birthdate',
    question: "When's your birthday?",
    body: 'You must be 18+ to use this app.',
    type: 'date',
    required: true,
    minAge: 18,
  },
  {
    id: 'gender',
    question: "What's your gender?",
    type: 'chips_single',
    required: true,
    options: ['Female', 'Male', 'Non-binary', 'Other', 'Prefer not to say'],
  },
  {
    id: 'languages',
    question: 'What languages do you speak fluently?',
    body: 'Select all that apply.',
    type: 'multi_select',
    required: true,
    options: [
      'English',
      'Spanish',
      'Mandarin',
      'Cantonese',
      'Korean',
      'Japanese',
      'Vietnamese',
      'Tagalog',
      'Hindi',
      'Arabic',
      'French',
      'German',
      'Italian',
      'Portuguese',
      'Russian',
      'Polish',
      'Armenian',
      'Persian',
      'Hebrew',
      'Thai',
      'Indonesian',
      'Turkish',
      'Greek',
      'Gujarati',
      'Dutch',
      'Swedish',
      'Czech',
      'Romanian',
      'Hungarian',
      'Ukrainian',
      'Bengali',
      'Punjabi',
      'Tamil',
      'Urdu',
      'Malay',
      'Other',
      'Prefer not to say',
    ],
  },
  {
    id: 'location',
    question: 'Where are you located?',
    body: "We'll use this to match you with people nearby. Your exact location stays private.",
    type: 'location_permission',
    required: true,
  },
]

// INTAKE (Final): Block 1 Life context → Block 2 Interests → Block 3 Topics → Block 4 Perspective → Block 5 Matching.
// Block 1: life chapter (stage) → everyday anchor (daily reality) only.
// Block 2: interests → curiosity → book/movie/place recs (no free afternoon).
export const INTAKE_STEPS: ProfileStep[] = [
  // Block 1 — Life context: stage → daily reality
  {
    id: 'q_life_chapter',
    question: 'What life chapter are you in now?',
    body: 'Select all that apply.',
    type: 'multi_select',
    required: true,
    options: [
      "I'm in college or university",
      "I'm in graduate school",
      'I recently graduated',
      "I'm early in my career",
      "I'm growing in my career",
      "I'm established in my career",
      "I'm building something (startup, project, business)",
      "I'm working independently or freelancing",
      "I'm transitioning into a new career",
      'I recently moved to this city',
      'I recently got married or entered a long-term partnership',
      "I'm exploring a new direction",
      "I'm taking time to figure out what's next",
      "I'm taking a break or sabbatical",
      "I'm starting a family",
      "I'm raising kids",
      "I'm caring for family members",
      "I'm semi-retired",
      "I'm retired",
    ],
  },
  {
    id: 'q_everyday_anchor',
    question: "What tends to anchor your day-to-day life right now?",
    body: 'Select all that apply.',
    type: 'multi_select',
    options: [
      'Work',
      'Building a business',
      'Side hustles',
      'Job search',
      'School',
      'Family life',
      'Parenting',
      'Family caregiving',
      'Romantic relationship',
      'Close friendships',
      'Fitness routine',
      'Creative projects',
      'Community or volunteering',
      'Faith or spiritual practice',
      'Travel',
      'Something else',
    ],
  },
  {
    id: 'q_work',
    question: 'What do you do for work?',
    body: 'A short phrase is perfect (e.g. “Graphic designer”, “Nurse”, “Software engineer”, “Barista”). If you’re between roles, feel free to share what you’ve been doing most recently.',
    type: 'text',
    required: false,
    placeholder: 'Short description (optional)',
  },
  // Block 2 — Interests: interests → curiosity → recs → free afternoon
  {
    id: 'q_interests',
    question: 'What are some of your interests?',
    body: 'Select all that apply.',
    type: 'multi_select',
    required: true,
    options: [
      'Reading',
      'Music',
      'Film & TV',
      'Podcasts',
      'Cooking',
      'Travel',
      'Fitness',
      'Dance',
      'Basketball',
      'Football',
      'Soccer',
      'Baseball',
      'Running',
      'Hiking',
      'Outdoors',
      'Yoga / Pilates',
      'Weightlifting',
      'Cycling',
      'Swimming',
      'Tennis',
      'Pickleball',
      'Photography',
      'Art & design',
      'Writing',
      'Gaming',
      'Entrepreneurship & startups',
      'Investing & finance',
      'History',
      'Science',
      'Philosophy',
      'Politics & current events',
    ],
  },
  {
    id: 'q_curiosity',
    question: "Which of these sounds most like something you'd pick up?",
    body: 'Select all that apply.',
    type: 'multi_select',
    options: [
      'Take a pottery class',
      'Learn how to paint',
      'Learn an instrument (e.g. guitar, piano, violin)',
      'Take a dance class (e.g. salsa, hip hop, ballroom)',
      'Take a cooking class',
      'Start learning a new language',
      'Join a storytelling workshop',
      'Take a photography course',
      'Start a fitness program',
      'Join a local sports league',
      'Take a coding course',
      'Take an AI course',
      'Take a philosophy class',
      'Take an improv class',
      'Take a human behavior course',
      'Join a public speaking group',
      'Take a course on how to build a business',
      'Take a class on personal finance or investing',
    ],
  },
  {
    id: 'q_book_recommendation',
    question: "What's a book you'd recommend?",
    body: "If you don't read, leave blank — we're not judging.",
    type: 'text',
    required: false,
    placeholder: 'Book recommendation',
  },
  {
    id: 'q_movie_show_recommendation',
    question: "What's a movie or show you'd recommend?",
    type: 'text',
    required: false,
    placeholder: 'Movie or show',
  },
  {
    id: 'q_role_model',
    question: 'Who is your role model?',
    type: 'text',
    required: false,
    placeholder: 'Name or description',
  },
  {
    id: 'q_role_model_why',
    question: 'What about them resonates with you?',
    type: 'text',
    required: false,
    placeholder: 'Optional',
  },
  {
    id: 'q_place_recommendation',
    question: "What's one place you'd recommend for someone to visit in your city?",
    body: 'Café, park, restaurant, hidden spot — whatever comes to mind.',
    type: 'text',
    required: false,
    placeholder: 'Place recommendation',
  },
  {
    id: 'q_avoid_topics',
    question: "Are there any topics you'd rather avoid in conversation?",
    body: 'Select all that apply. We use this to avoid suggesting these as conversation starters.',
    type: 'multi_select',
    required: false,
    options: [
      'Politics',
      'Religion',
      'Work & career',
      'Relationship status',
      'Health',
      'Personal finances',
      'Nothing in particular',
      'Prefer not to say',
    ],
  },
  // Matching preferences
  {
    id: 'q_openness',
    question: 'Who would you be open to meet for a Fika?',
    type: 'chips_single',
    required: true,
    options: [
      "Someone I'd instantly relate to",
      'Someone outside my usual bubble',
      'Someone whose perspective challenges mine',
      "I'm open to anyone",
    ],
  },
  {
    id: 'gender_preference',
    question: "Do you have a gender preference for who you'd like to meet?",
    body: 'Just a friendly FYI — Fika is solely intended for platonic conversations.',
    type: 'chips_single',
    required: true,
    options: ['No preference', 'Same gender', 'Different gender'],
  },
  {
    id: 'age_preference',
    question: "Do you have an age preference for who you'd like to meet?",
    body: "Either way works! While meeting people in a similar life stage gives you both something to relate to, meeting people in different phases of life can bring fresh perspectives.",
    type: 'chips_single',
    required: true,
    options: ['Open to any age/life stage', 'Prefer around my age'],
  },
  {
    id: 'q_hoping_for',
    question: 'What are you hoping for from Fika?',
    body: 'No wrong answer — we use this to match you with people who want similar things.',
    type: 'chips_single',
    required: true,
    options: [
      'Conversation with new people — not necessarily friendship',
      'Meeting people nearby — open to friendship if it happens',
      'Actively looking for new friends',
    ],
  },
  {
    id: 'q_what_makes_great_fika',
    question: 'What would make a great Fika conversation for you?',
    body: 'Select all that apply.',
    type: 'multi_select',
    required: true,
    options: [
      'Swapping stories from our lives (chapters, how we got here)',
      'Stuff we’re into lately (books, shows, podcasts, games)',
      'Recent travel and places you’ve visited',
      'What we’re working on (work or projects)',
      'Giving/getting advice for professional & personal growth',
      'Life in our city (neighborhoods, restaurants, hangout spots)',
      'Big questions and how we see the world',
      'Hobbies and things we’d like to try next',
    ],
  },
  {
    id: 'q_radius',
    question: 'How far are you willing to travel for a Fika?',
    body: "We'll suggest meetup spots for your Fika within this distance.",
    type: 'chips_single',
    required: true,
    options: ['5 miles', '10 miles', '25 miles', '50 miles'],
  },
  {
    id: 'confirm_intent',
    question: 'Fika is built for thoughtful, platonic connection.',
    body: "We're here to help people meet others nearby for real conversation. Any behavior that doesn't align may result in removal.",
    type: 'chips_single',
    required: true,
    options: ["I'm in"],
  },
]

export const TOTAL_ONBOARDING_STEPS = PROFILE_STEPS.length + INTAKE_STEPS.length
