/** ~250 professions for searchable select. No slashes; use "and", "or", commas. */
export const PROFESSION_OPTIONS: string[] = [
  'Accountant',
  'Actor',
  'Actuary',
  'Acupuncturist',
  'Administrative assistant',
  'Advertising manager',
  'Aerospace engineer',
  'Agricultural worker',
  'Airline pilot',
  'Analyst',
  'Anesthesiologist',
  'Architect',
  'Archivist',
  'Artist',
  'Athletic trainer',
  'Attorney',
  'Auditor',
  'Baker',
  'Banker',
  'Barber',
  'Bartender',
  'Biologist',
  'Biomedical engineer',
  'Bookkeeper',
  'Brand manager',
  'Brewer',
  'Building inspector',
  'Business analyst',
  'Business development',
  'Business owner',
  'Buyer',
  'Cabinet maker',
  'Carpenter',
  'Cartographer',
  'Chef',
  'Chemical engineer',
  'Chemist',
  'Childcare worker',
  'Chiropractor',
  'Civil engineer',
  'Coach',
  'Compliance officer',
  'Computer programmer',
  'Construction manager',
  'Consultant',
  'Content strategist',
  'Contractor',
  'Copywriter',
  'Corrections officer',
  'Counselor',
  'Court reporter',
  'Curator',
  'Customer success',
  'Data analyst',
  'Data scientist',
  'Database administrator',
  'Dental hygienist',
  'Dentist',
  'Designer',
  'Developer',
  'Dietitian',
  'Director',
  'Doctor',
  'Driver',
  'Economist',
  'Editor',
  'Educator',
  'Electrician',
  'Emergency medical technician',
  'Engineer',
  'Entrepreneur',
  'Environmental scientist',
  'Event planner',
  'Executive assistant',
  'Farmer',
  'Financial advisor',
  'Financial analyst',
  'Firefighter',
  'Fitness instructor',
  'Flight attendant',
  'Florist',
  'Food scientist',
  'Fundraiser',
  'Geologist',
  'Graphic designer',
  'Hair stylist',
  'Health educator',
  'Healthcare administrator',
  'Historian',
  'Home health aide',
  'Hotel manager',
  'Human resources',
  'Illustrator',
  'Industrial designer',
  'Insurance agent',
  'Interior designer',
  'Interpreter',
  'Inventor',
  'Investment banker',
  'Journalist',
  'Judge',
  'Laboratory technician',
  'Landscape architect',
  'Lawyer',
  'Librarian',
  'Loan officer',
  'Lobbyist',
  'Logistician',
  'Machinist',
  'Management consultant',
  'Manager',
  'Marine biologist',
  'Market researcher',
  'Marketing manager',
  'Massage therapist',
  'Mathematician',
  'Mechanic',
  'Media planner',
  'Medical assistant',
  'Medical technologist',
  'Mental health counselor',
  'Merchandiser',
  'Microbiologist',
  'Military',
  'Museum curator',
  'Music producer',
  'Musician',
  'Nanny',
  'Network administrator',
  'Neurologist',
  'Nurse',
  'Nurse practitioner',
  'Nutritionist',
  'Occupational therapist',
  'Operations manager',
  'Optometrist',
  'Paralegal',
  'Paramedic',
  'Pastor',
  'Pathologist',
  'Pediatrician',
  'Personal trainer',
  'Pharmacist',
  'Pharmacy technician',
  'Photographer',
  'Physical therapist',
  'Physician',
  'Physician assistant',
  'Physicist',
  'Pilot',
  'Plumber',
  'Police officer',
  'Political scientist',
  'Professor',
  'Project manager',
  'Psychiatrist',
  'Psychologist',
  'Public relations',
  'Publisher',
  'Purchasing agent',
  'Quality assurance',
  'Radiologist',
  'Real estate agent',
  'Receptionist',
  'Recruiter',
  'Registered nurse',
  'Reporter',
  'Researcher',
  'Restaurant manager',
  'Retail manager',
  'Sales representative',
  'Sanitation worker',
  'Scientist',
  'Screenwriter',
  'Security guard',
  'Social media manager',
  'Social worker',
  'Software engineer',
  'Speech therapist',
  'Statistician',
  'Stock broker',
  'Store manager',
  'Student',
  'Surgeon',
  'Surveyor',
  'Teacher',
  'Technical writer',
  'Technician',
  'Therapist',
  'Translator',
  'Travel agent',
  'Truck driver',
  'Tutor',
  'Urban planner',
  'Veterinarian',
  'Veterinary technician',
  'Video editor',
  'Videographer',
  'Volunteer coordinator',
  'Waiter or waitress',
  'Web developer',
  'Writer',
  'Youth worker',
  'Academic researcher',
  'Animator',
  'Arborist',
  'Art director',
  'Art therapist',
  'Astronomer',
  'Athlete',
  'Automotive technician',
  'Bailiff',
  'Baker and pastry chef',
  'Behavioral analyst',
  'Benefits administrator',
  'Biochemist',
  'Biotech researcher',
  'Budget analyst',
  'Building maintenance',
  'Camp counselor',
  'Career coach',
  'Case manager',
  'Caterer',
  'Claims adjuster',
  'Clinical psychologist',
  'Clergy',
  'Community organizer',
  'Composer',
  'Conservation scientist',
  'Construction worker',
  'Coroner',
  'Cosmetologist',
  'Cost estimator',
  'Credit analyst',
  'Criminal investigator',
  'Customer service representative',
  'Dancer',
  'Data entry clerk',
  'Dental assistant',
  'Dermatologist',
  'Detective',
  'Diagnostic technician',
  'Dietetic technician',
  'Diplomat',
  'Dispensing optician',
  'Distiller',
  'Drafting technician',
  'Ecology specialist',
  'Election official',
  'Electronics technician',
  'Elementary school teacher',
  'EMT',
  'Endocrinologist',
  'Energy auditor',
  'Engineering technician',
  'Environmental engineer',
  'Epidemiologist',
  'Estate planner',
  'Executive coach',
  'Exhibit designer',
  'Facilities manager',
  'Family therapist',
  'Film director',
  'Financial planner',
  'Fire inspector',
  'Fitness trainer',
  'Forensic scientist',
  'Franchise owner',
  'Funeral director',
  'Game designer',
  'Genetic counselor',
  'Geographer',
  'Grant writer',
  'Grants administrator',
  'Guidance counselor',
  'Hazardous materials worker',
  'Headhunter',
  'Hearing officer',
  'High school teacher',
  'Home inspector',
  'Horticulturist',
  'Hospital administrator',
  'Hotel clerk',
  'Immigration consultant',
  'Industrial engineer',
  'Information security analyst',
  'Instructional designer',
  'Insurance underwriter',
  'Interpreter and translator',
  'Investment analyst',
  'Jeweler',
  'Judge and hearing officer',
  'Kindergarten teacher',
  'Landscape designer',
  'Legislator',
  'Loan counselor',
  'Locksmith',
  'Logistics analyst',
  'Makeup artist',
  'Management analyst',
  'Marriage therapist',
  'Mechanical engineer',
  'Medical examiner',
  'Medical records technician',
  'Meeting planner',
  'Mental health worker',
  'Meteorologist',
  'Midwife',
  'Military officer',
  'Mining engineer',
  'Mortician',
  'Museum educator',
  'Music teacher',
  'Nurse midwife',
  'Occupational health specialist',
  'Office manager',
  'Oncologist',
  'Orthodontist',
  'Orthopedic surgeon',
  'Outreach coordinator',
  'Parole officer',
  'Patent agent',
  'Payroll specialist',
  'Pediatric nurse',
  'Personal care aide',
  'Pet groomer',
  'Pharmacologist',
  'Phlebotomist',
  'Photography assistant',
  'Physicist and astronomer',
  'Pilot and navigator',
  'Podiatrist',
  'Policy analyst',
  'Postal worker',
  'Precision machinist',
  'Principal',
  'Printing worker',
  'Prison guard',
  'Producer',
  'Product manager',
  'Production manager',
  'Program coordinator',
  'Programmer analyst',
  'Property manager',
  'Prosthetist',
  'Psychiatric aide',
  'Public administrator',
  'Public health worker',
  'Purchasing manager',
  'Radiologic technologist',
  'Realtor',
  'Recreation worker',
  'Referee',
  'Religious educator',
  'Respiratory therapist',
  'Risk manager',
  'Sales manager',
  'School counselor',
  'Sculptor',
  'Security analyst',
  'Set designer',
  'Ship captain',
  'Social scientist',
  'Sociologist',
  'Software developer',
  'Sound engineer',
  'Special education teacher',
  'Speech pathologist',
  'Sports agent',
  'Staffing coordinator',
  'Substance abuse counselor',
  'Surgeon assistant',
  'Tax preparer',
  'Teaching assistant',
  'Telecommunications worker',
  'Therapeutic recreation',
  'Tour guide',
  'Traffic technician',
  'Training specialist',
  'Underwriter',
  'Upholsterer',
  'Veterinary assistant',
  'Vocational counselor',
  'Warehouse worker',
  'Wedding planner',
  'Welder',
  'Wildlife biologist',
  'Zookeeper',
  'Other',
  'Prefer not to say',
]
