import { PROFESSION_OPTIONS } from '@/lib/profession-options'

function mergeUniqueCaseInsensitive(priority: string[], rest: string[]): string[] {
  const seen = new Set<string>()
  const out: string[] = []
  for (const raw of [...priority, ...rest]) {
    const t = raw.trim()
    if (!t) continue
    const k = t.toLowerCase()
    if (seen.has(k)) continue
    seen.add(k)
    out.push(t)
  }
  return out
}

/**
 * Order matters: inclusive life situations, gig/non-W-2, tech/creator synonyms,
 * trades and public-sector picks, then the rest of `PROFESSION_OPTIONS` (deduped).
 */
const WORK_ROLE_PRIORITY: string[] = [
  // Inclusive — not in paid work or between paths
  'Currently unemployed',
  'Between jobs',
  'Stay-at-home parent',
  'Full-time caregiver at home',
  'Taking a career break',
  'On sabbatical',
  'Retired',
  'Student',
  // Non–W-2 and flexible work
  'Gig worker',
  'Freelancer',
  'Independent contractor',
  'Part-time worker',
  'Seasonal worker',
  'Working night shifts',
  'Apprentice',
  'AmeriCorps member',
  'Between contracts',
  'Work visa / limited work authorization',
  // Founders & leadership
  'Founder',
  'Co-founder',
  'Entrepreneur',
  'Chief of staff',
  // Product, program, ops, revenue
  'Product manager',
  'Product designer',
  'Project manager',
  'Program manager',
  'Technical program manager',
  'Operations manager',
  'Business analyst',
  'RevOps',
  'Sales operations',
  'Marketing operations',
  // Engineering & IT (modern titles + synonyms)
  'Software engineer',
  'Software developer',
  'Programmer',
  'Full-stack developer',
  'Frontend developer',
  'Backend developer',
  'Mobile developer',
  'Web developer',
  'DevOps engineer',
  'Site reliability engineer',
  'Platform engineer',
  'Data engineer',
  'Machine learning engineer',
  'ML engineer',
  'AI engineer',
  'Solutions engineer',
  'Sales engineer',
  'Developer relations',
  'Developer advocate',
  'Security engineer',
  'Cybersecurity analyst',
  'Information security analyst',
  'IT support specialist',
  'Help desk technician',
  'Systems administrator',
  'Network engineer',
  'Cloud engineer',
  'QA engineer',
  'Quality assurance engineer',
  'Test engineer',
  'Automation engineer',
  'Embedded software engineer',
  'Firmware engineer',
  'Game developer',
  'Game designer',
  'Technical writer',
  'Scrum master',
  'Engineering manager',
  'Data scientist',
  'Data analyst',
  'Business intelligence analyst',
  'Research scientist',
  // Design & UX
  'Designer',
  'UX designer',
  'UI designer',
  'UX researcher',
  'Interaction designer',
  'Content designer',
  // Go-to-market
  'Marketing manager',
  'Sales manager',
  'Account executive',
  'Account manager',
  'Customer success manager',
  'Customer success',
  'Partnerships manager',
  'Growth marketer',
  // Healthcare (incl. allied health)
  'Registered nurse',
  'Nurse practitioner',
  'Nurse',
  'Medical assistant',
  'Physician',
  'Doctor',
  'Dentist',
  'Pharmacist',
  'Physical therapist',
  'Dental hygienist',
  'Dental assistant',
  'Home health aide',
  'Phlebotomist',
  'Sterile processing technician',
  'Veterinary technician',
  'Pharmacy technician',
  'Medical coder',
  'Medical billing specialist',
  'Occupational therapy assistant',
  'Radiologic technologist',
  // Education
  'Teacher',
  'Professor',
  'Teaching assistant',
  'School counselor',
  'School administrator',
  'Principal',
  'Substitute teacher',
  'Instructional coach',
  // Trades, logistics, field work
  'Electrician',
  'Plumber',
  'Carpenter',
  'Welder',
  'Mechanic',
  'HVAC technician',
  'Construction worker',
  'Field service technician',
  'Warehouse worker',
  'Warehouse associate',
  'Forklift operator',
  'Inventory specialist',
  'Truck driver',
  'Delivery driver',
  'Commercial driver',
  'Automotive technician',
  'Diesel mechanic',
  'Lineworker',
  'Longshore worker',
  'Aviation ground crew',
  'Building maintenance technician',
  // Hospitality, retail, food service
  'Chef',
  'Line cook',
  'Baker',
  'Barista',
  'Waiter or waitress',
  'Cashier',
  'Retail manager',
  'Store manager',
  'Hotel manager',
  'Housekeeper',
  'Janitor',
  // Office & people-facing
  'Administrative assistant',
  'Receptionist',
  'Office manager',
  'Customer service representative',
  'Call center representative',
  'Sales representative',
  'Recruiter',
  'Human resources',
  'People operations',
  // Beauty & wellness
  'Hair stylist',
  'Massage therapist',
  'Cosmetologist',
  'Personal trainer',
  'Esthetician',
  'Nail technician',
  // Safety & public service
  'Police officer',
  'Firefighter',
  'Paramedic',
  'EMT',
  'Security guard',
  'Corrections officer',
  'Probation officer',
  '911 dispatcher',
  'Military',
  'Active duty military',
  'Military reservist',
  'Veteran',
  // Care & community
  'Social worker',
  'Case manager',
  'Childcare worker',
  'Nanny',
  'Therapist',
  'Counselor',
  'Peer support specialist',
  // Nonprofit & public sector
  'Grant writer',
  'Program officer',
  'Nonprofit director',
  'Community organizer',
  'City planner',
  'Policy analyst',
  'Legislative aide',
  // Creative, media & creator economy
  'Photographer',
  'Writer',
  'Journalist',
  'Artist',
  'Musician',
  'Video editor',
  'Film editor',
  'Producer',
  'Director',
  'Content creator',
  'Influencer',
  'Streamer',
  'YouTuber',
  'Podcast producer',
  'Podcast host',
  'Voice actor',
  'Motion designer',
  'Animator',
  'Sound designer',
  'Social media manager',
  // Professional services
  'Attorney',
  'Lawyer',
  'Paralegal',
  'Accountant',
  'Bookkeeper',
  'Financial advisor',
  'Real estate agent',
  'Insurance agent',
  'Mortgage loan officer',
  // Other common paths
  'Farmer',
  'Scientist',
  'Researcher',
  'Engineer',
  'Architect',
  'Pilot',
  'Flight attendant',
  'Librarian',
  'Curator',
  'Actuary',
]

export const WORK_ROLE_OPTIONS: string[] = mergeUniqueCaseInsensitive(WORK_ROLE_PRIORITY, PROFESSION_OPTIONS)
