export const WORK_ROLE_FEATURED = [
  'Between jobs',
  'Taking a break',
  'Student',
  'Retired',
  'Freelancer / Contractor',
]

export const WORK_ROLE_OPTIONS: string[] = [
  // Life situations / non-standard
  'Between jobs',
  'Taking a break',
  'On sabbatical',
  'Retired',
  'Student',
  'Stay-at-home parent',
  'Freelancer / Contractor',
  'Self-employed',
  'Volunteer',

  // Startup / Founder
  'Founder / Co-founder',
  'CEO',
  'COO',
  'CTO / VP Engineering',
  'CFO',
  'Startup Employee',
  'Entrepreneur',
  'Angel Investor',
  'Venture Capitalist',

  // Tech — Engineering
  'Software Engineer',
  'Frontend Engineer',
  'Backend Engineer',
  'Full-Stack Engineer',
  'Mobile Engineer',
  'iOS Engineer',
  'Android Engineer',
  'Machine Learning Engineer',
  'AI Engineer',
  'Data Engineer',
  'DevOps / SRE',
  'Platform Engineer',
  'Cloud Engineer',
  'Security Engineer',
  'Embedded Systems Engineer',
  'QA / Test Engineer',
  'Engineering Manager',

  // Tech — Product & Design
  'Product Manager',
  'Product Designer',
  'UX Designer',
  'UI Designer',
  'UX Researcher',
  'Design Lead / Head of Design',
  'Creative Director',
  'Technical Program Manager',

  // Tech — Data & AI
  'Data Scientist',
  'Data Analyst',
  'Business Intelligence Analyst',
  'AI Researcher',
  'ML Researcher',
  'Quantitative Analyst',

  // Business & Strategy
  'Management Consultant',
  'Strategy Consultant',
  'Business Analyst',
  'Operations Manager',
  'Project Manager',
  'Program Manager',
  'Business Development',
  'Account Manager',
  'Customer Success',
  'Sales Manager',
  'Account Executive',

  // Marketing & Communications
  'Marketing Manager',
  'Growth Marketer',
  'Content Marketer',
  'Brand Manager',
  'Social Media Manager',
  'Public Relations',
  'Communications Manager',
  'Copywriter',
  'SEO Specialist',
  'Performance Marketer',

  // Finance
  'Investment Banker',
  'Private Equity',
  'Hedge Fund',
  'Financial Analyst',
  'Accountant / CPA',
  'Financial Advisor / CFP',
  'Wealth Manager',
  'Actuary',
  'Risk Manager',
  'Compliance Officer',
  'Trader',

  // Legal
  'Attorney / Lawyer',
  'Corporate Counsel',
  'Paralegal',
  'Public Defender',
  'District Attorney',
  'Judge',

  // Healthcare & Medicine
  'Physician / Doctor',
  'Surgeon',
  'Nurse / NP',
  'Nurse Practitioner',
  'Nurse (RN)',
  'Physician Assistant',
  'Dentist',
  'Dental Hygienist',
  'Pharmacist',
  'Physical Therapist',
  'Occupational Therapist',
  'Psychologist',
  'Psychiatrist',
  'Therapist / Counselor',
  'Social Worker',
  'Medical Researcher',
  'Public Health Professional',
  'Radiologist',
  'Anesthesiologist',
  'Veterinarian',
  'EMT / Paramedic',
  'Optometrist',
  'Chiropractor',

  // Education
  'Teacher (K-12)',
  'High School Teacher',
  'College Professor',
  'School Administrator',
  'Education Researcher',
  'Tutor',
  'School Counselor',
  'Academic Advisor',

  // Science & Research
  'Researcher',
  'Scientist',
  'Biologist',
  'Chemist',
  'Physicist',
  'Environmental Scientist',
  'Neuroscientist',
  'Biomedical Engineer',
  'Geologist',
  'Epidemiologist',

  // Engineering (non-software)
  'Civil Engineer',
  'Mechanical Engineer',
  'Electrical Engineer',
  'Chemical Engineer',
  'Aerospace Engineer',
  'Environmental Engineer',
  'Structural Engineer',
  'Industrial Engineer',
  'Materials Engineer',
  'Nuclear Engineer',

  // Architecture & Design
  'Architect',
  'Interior Designer',
  'Urban Planner',
  'Landscape Architect',

  // Creative & Media
  'Graphic Designer',
  'Visual Artist',
  'Illustrator',
  'Photographer',
  'Videographer',
  'Filmmaker / Director',
  'Musician',
  'Actor / Performer',
  'Writer / Author',
  'Journalist',
  'Editor',
  'Animator',
  'Motion Designer',
  'Fashion Designer',
  'Art Director',
  'Content Creator',
  'Podcast Producer',

  // Government, Policy & Non-profit
  'Government Employee',
  'Policy Analyst',
  'Non-profit Professional',
  'Social Impact',
  'Community Organizer',
  'Lobbyist',
  'Military Officer',
  'Diplomat',
  'Elected Official',

  // Real Estate & Property
  'Real Estate Agent',
  'Real Estate Developer',
  'Property Manager',
  'Real Estate Investor',
  'Mortgage Broker',

  // Trades & Skilled Work
  'Electrician',
  'Plumber',
  'HVAC Technician',
  'Carpenter',
  'Construction Manager',
  'General Contractor',
  'Welder',

  // Hospitality & Food
  'Chef',
  'Restaurant Manager',
  'Bartender',
  'Barista',
  'Sommelier',
  'Event Planner',
  'Hotel Manager',
  'Catering Manager',

  // HR, Admin & Operations
  'HR Manager',
  'Recruiter / Talent Acquisition',
  'Executive Assistant',
  'Office Manager',
  'Operations Analyst',
  'Supply Chain Manager',
  'Logistics Manager',
  'Procurement Manager',
  'Retail Manager',
  'Store Manager',

  // Other
  'Financial Planner',
  'Insurance Agent',
  'Flight Attendant',
  'Pilot',
  'Personal Trainer',
  'Sports Coach',
  'Athlete',
  'Physical Education Teacher',
]
